import pandas as pd
import json
import pandas as pd
from datetime import datetime
from flask import send_file

def process_Dn_file(name,uploaded_data, filter_data):
    try:       # -*- coding: utf-8 -*-
      """filter_dn.ipynb

      Automatically generated by Colab.

      Original file is located at
          https://colab.research.google.com/drive/1LpcHbpowgFL88hOYADfk3u8ZqzvOqhlR
      """

      # from datetime import datetime

      selectionData = filter_data

      # Convert string to datetime
      start = datetime.strptime(selectionData["startDate"], "%Y-%m-%d")
      end = datetime.strptime(selectionData["endDate"], "%Y-%m-%d")
      print(start,end)
      # Calculate date difference
      diff_date = (end - start).days
      print(diff_date)

      
      # print("Date Difference in Days:", diff_date)  # Output: 7

      data=uploaded_data
      
      final_data = {}

      # from typing_extensions import final
      # import pandas as pd

      # Utility function
      def check(dic, name):
          return name in dic

      all_cols = set()
      final_data = {}
      if(name == "Shipment"):
          final_data = {
              "dn_count":0,
              "total_hour":0,
              "total_quantity":0,
              "total_item":0,
              "total_dn_value":0,
              "load_data":{},
              "priority_data":{}
          }
          if diff_date == 0:
            print("1")
            for ob in data:
              final_data["dn_count"] += ob["dn_count"]
              final_data["total_hour"] += ob["total_hour"]
              final_data["total_quantity"] += ob["total_quantity"]
              final_data["total_item"] += ob["total_item"]
              final_data["total_dn_value"] += ob["total_dn_value"]
              final_data["load_data"][ob["date"]] = {}
              for key,value in ob["ship_priority"].items():
                if (key in final_data["load_data"][ob["date"]]):
                  final_data["load_data"][ob["date"]][key][0] += value[0]
                  final_data["load_data"][ob["date"]][key][1] += value[1]
                  final_data["load_data"][ob["date"]][key][2] += value[2]
                  final_data["load_data"][ob["date"]][key][3] += value[3]
                  final_data["load_data"][ob["date"]][key][4] += value[4]
                else:
                  final_data["load_data"][ob["date"]][key] = value
                if key in final_data["priority_data"]:
                  final_data["priority_data"][key][0] += value[0]
                  final_data["priority_data"][key][1] += value[1]
                  final_data["priority_data"][key][2] += value[2]
                  final_data["priority_data"][key][3] += value[3]
                  final_data["priority_data"][key][4] += value[4]
                else:
                  final_data["priority_data"][key] = value
          elif 0 < diff_date <= 6:
            print("2")
            for ob in data:
              final_data["dn_count"] += ob["dn_count"]
              final_data["total_hour"] += ob["total_hour"]
              final_data["total_quantity"] += ob["total_quantity"]
              final_data["total_item"] += ob["total_item"]
              final_data["total_dn_value"] += ob["total_dn_value"]
              final_data["load_data"][ob["date"]] = {}
              for key,value in ob["ship_priority"].items():
                if (key in final_data["load_data"][ob["date"]]):
                  final_data["load_data"][ob["date"]][key][0] += value[0]
                  final_data["load_data"][ob["date"]][key][1] += value[1]
                  final_data["load_data"][ob["date"]][key][2] += value[2]
                  final_data["load_data"][ob["date"]][key][3] += value[3]
                  final_data["load_data"][ob["date"]][key][4] += value[4]
                else:
                  final_data["load_data"][ob["date"]][key] = value
                if key in final_data["priority_data"]:
                  final_data["priority_data"][key][0] += value[0]
                  final_data["priority_data"][key][1] += value[1]
                  final_data["priority_data"][key][2] += value[2]
                  final_data["priority_data"][key][3] += value[3]
                  final_data["priority_data"][key][4] += value[4]
                else:
                  final_data["priority_data"][key] = value
          elif 6 < diff_date <= 59:
            print("3")
            for ob in data:
              final_data["dn_count"] += ob["dn_count"]
              final_data["total_hour"] += ob["total_hour"]
              final_data["total_quantity"] += ob["total_quantity"]
              final_data["total_item"] += ob["total_item"]
              final_data["total_dn_value"] += ob["total_dn_value"]
              curr_week = (((datetime.strptime(ob["date"], "%Y-%m-%d")).date()- start.date()).days // 7) + 1
              week_key = f"Week {int(curr_week)}"
              final_data["load_data"][week_key] = {}
              for key,value in ob["ship_priority"].items():
                if (key in final_data["load_data"][week_key]):
                  final_data["load_data"][week_key][key][0] += value[0]
                  final_data["load_data"][week_key][key][1] += value[1]
                  final_data["load_data"][week_key][key][2] += value[2]
                  final_data["load_data"][week_key][key][3] += value[3]
                  final_data["load_data"][week_key][key][4] += value[4]
                else:
                  final_data["load_data"][week_key][key] = value
                if key in final_data["priority_data"]:
                  final_data["priority_data"][key][0] += value[0]
                  final_data["priority_data"][key][1] += value[1]
                  final_data["priority_data"][key][2] += value[2]
                  final_data["priority_data"][key][3] += value[3]
                  final_data["priority_data"][key][4] += value[4]
                else:
                  final_data["priority_data"][key] = value
          elif diff_date > 59:
            print("4")
            for ob in data:
              final_data["dn_count"] += ob["dn_count"]
              final_data["total_hour"] += ob["total_hour"]
              final_data["total_quantity"] += ob["total_quantity"]
              final_data["total_item"] += ob["total_item"]
              final_data["total_dn_value"] += ob["total_dn_value"]
              curr_mon = (((datetime.strptime(ob["date"], "%Y-%m-%d")).date() - start.date()).days // 30) + 1
              mon_key = f"mon {int(curr_mon)}"
              final_data["load_data"][mon_key] = {}
              for key,value in ob["ship_priority"].items():
                if (key in final_data["load_data"][mon_key]):
                  final_data["load_data"][mon_key][key][0] += value[0]
                  final_data["load_data"][mon_key][key][1] += value[1]
                  final_data["load_data"][mon_key][key][2] += value[2]
                  final_data["load_data"][mon_key][key][3] += value[3]
                  final_data["load_data"][mon_key][key][4] += value[4]
                else:
                  final_data["load_data"][mon_key][key] = value
                if key in final_data["priority_data"]:
                  final_data["priority_data"][key][0] += value[0]
                  final_data["priority_data"][key][1] += value[1]
                  final_data["priority_data"][key][2] += value[2]
                  final_data["priority_data"][key][3] += value[3]
                  final_data["priority_data"][key][4] += value[4]
                else:
                  final_data["priority_data"][key] = value
      else:
        final_data = {
              "dn_count":0,
              "total_through_put_to_pic_hour":0,
              "total_pic_to_pac_hour":0,
              "total_pac_to_inv_hour":0,
              "total_quantity":0,
              "total_lines":0,
              "total_dn_value":0,
              "load_data":{},#3
              "priority_data":{}
          }
        if diff_date == 0:
          print("5")
          for ob in data:
            final_data["dn_count"] += ob["dn_count"]
            final_data["total_through_put_to_pic_hour"] += ob["total_through_put_to_pic_hour"]
            final_data["total_pic_to_pac_hour"] += ob["total_pic_to_pac_hour"]
            final_data["total_pac_to_inv_hour"] += ob["total_pac_to_inv_hour"]
            final_data["total_quantity"] += ob["total_quantity"]
            final_data["total_lines"] += ob["total_lines"]
            final_data["total_dn_value"] += ob["total_dn_value"]
            final_data["load_data"][ob["date"]] = {}
            for key,value in ob["ship_priority"].items():
              if (key in final_data["load_data"][ob["date"]]):
                final_data["load_data"][ob["date"]][key][0] += value[0]
                final_data["load_data"][ob["date"]][key][1] += value[1]
                final_data["load_data"][ob["date"]][key][2] += value[2]
                final_data["load_data"][ob["date"]][key][3] += value[3]
                final_data["load_data"][ob["date"]][key][4] += value[4]
                final_data["load_data"][ob["date"]][key][5] += value[5]
                final_data["load_data"][ob["date"]][key][6] += value[6]
              else:
                final_data["load_data"][ob["date"]][key] = value
              if key in final_data["priority_data"]:
                  final_data["priority_data"][key][0] += value[0]
                  final_data["priority_data"][key][1] += value[1]
                  final_data["priority_data"][key][2] += value[2]
                  final_data["priority_data"][key][3] += value[3]
                  final_data["priority_data"][key][4] += value[4]
                  final_data["priority_data"][key][5] += value[5]
                  final_data["priority_data"][key][6] += value[6]
              else:
                  final_data["priority_data"][key] = value
        elif 0 < diff_date <= 6:
          print("6")
          for ob in data:
            final_data["dn_count"] += ob["dn_count"]
            final_data["total_through_put_to_pic_hour"] += ob["total_through_put_to_pic_hour"]
            final_data["total_pic_to_pac_hour"] += ob["total_pic_to_pac_hour"]
            final_data["total_pac_to_inv_hour"] += ob["total_pac_to_inv_hour"]
            final_data["total_quantity"] += ob["total_quantity"]
            final_data["total_lines"] += ob["total_lines"]
            final_data["total_dn_value"] += ob["total_dn_value"]
            final_data["load_data"][ob["date"]] = {}
            for key,value in ob["ship_priority"].items():
              if (key in final_data["load_data"][ob["date"]]):
                final_data["load_data"][ob["date"]][key][0] += value[0]
                final_data["load_data"][ob["date"]][key][1] += value[1]
                final_data["load_data"][ob["date"]][key][2] += value[2]
                final_data["load_data"][ob["date"]][key][3] += value[3]
                final_data["load_data"][ob["date"]][key][4] += value[4]
                final_data["load_data"][ob["date"]][key][5] += value[5]
                final_data["load_data"][ob["date"]][key][6] += value[6]
              else:
                final_data["load_data"][ob["date"]][key] = value
              if key in final_data["priority_data"]:
                  final_data["priority_data"][key][0] += value[0]
                  final_data["priority_data"][key][1] += value[1]
                  final_data["priority_data"][key][2] += value[2]
                  final_data["priority_data"][key][3] += value[3]
                  final_data["priority_data"][key][4] += value[4]
                  final_data["priority_data"][key][5] += value[5]
                  final_data["priority_data"][key][6] += value[6]
              else:
                  final_data["priority_data"][key] = value
        elif 6 < diff_date <= 59:
          print("7")
          for ob in data:
            final_data["dn_count"] += ob["dn_count"]
            final_data["total_through_put_to_pic_hour"] += ob["total_through_put_to_pic_hour"]
            final_data["total_pic_to_pac_hour"] += ob["total_pic_to_pac_hour"]
            final_data["total_pac_to_inv_hour"] += ob["total_pac_to_inv_hour"]
            final_data["total_quantity"] += ob["total_quantity"]
            final_data["total_lines"] += ob["total_lines"]
            final_data["total_dn_value"] += ob["total_dn_value"]
            curr_week = (((datetime.strptime(ob["date"], "%Y-%m-%d")).date() - start.date()).days // 7) + 1
            week_key = f"Week {int(curr_week)}"
            final_data["load_data"][week_key] = {}
            for key,value in ob["ship_priority"].items():
              if (key in final_data["load_data"][week_key]):
                final_data["load_data"][week_key][key][0] += value[0]
                final_data["load_data"][week_key][key][1] += value[1]
                final_data["load_data"][week_key][key][2] += value[2]
                final_data["load_data"][week_key][key][3] += value[3]
                final_data["load_data"][week_key][key][4] += value[4]
                final_data["load_data"][week_key][key][5] += value[5]
                final_data["load_data"][week_key][key][6] += value[6]
              else:
                final_data["load_data"][week_key][key] = value
              if key in final_data["priority_data"]:
                  final_data["priority_data"][key][0] += value[0]
                  final_data["priority_data"][key][1] += value[1]
                  final_data["priority_data"][key][2] += value[2]
                  final_data["priority_data"][key][3] += value[3]
                  final_data["priority_data"][key][4] += value[4]
                  final_data["priority_data"][key][5] += value[5]
                  final_data["priority_data"][key][6] += value[6]
              else:
                  final_data["priority_data"][key] = value
        elif diff_date > 59:
          print("8")
          for ob in data:
            final_data["dn_count"] += ob["dn_count"]
            final_data["total_through_put_to_pic_hour"] += ob["total_through_put_to_pic_hour"]
            final_data["total_pic_to_pac_hour"] += ob["total_pic_to_pac_hour"]
            final_data["total_pac_to_inv_hour"] += ob["total_pac_to_inv_hour"]
            final_data["total_quantity"] += ob["total_quantity"]
            final_data["total_lines"] += ob["total_lines"]
            final_data["total_dn_value"] += ob["total_dn_value"]
            curr_mon = (((datetime.strptime(ob["date"], "%Y-%m-%d")).date() - start.date()).days // 30) + 1
            mon_key = f"mon {int(curr_mon)}"
            final_data["load_data"][mon_key] = {}
            for key,value in ob["ship_priority"].items():
              if (key in final_data["load_data"][mon_key]):
                final_data["load_data"][mon_key][key][0] += value[0]
                final_data["load_data"][mon_key][key][1] += value[1]
                final_data["load_data"][mon_key][key][2] += value[2]
                final_data["load_data"][mon_key][key][3] += value[3]
                final_data["load_data"][mon_key][key][4] += value[4]
                final_data["load_data"][mon_key][key][5] += value[5]
                final_data["load_data"][mon_key][key][6] += value[6]
              else:
                final_data["load_data"][mon_key][key] = value
              if key in final_data["priority_data"]:
                  final_data["priority_data"][key][0] += value[0]
                  final_data["priority_data"][key][1] += value[1]
                  final_data["priority_data"][key][2] += value[2]
                  final_data["priority_data"][key][3] += value[3]
                  final_data["priority_data"][key][4] += value[4]
                  final_data["priority_data"][key][5] += value[5]
                  final_data["priority_data"][key][6] += value[6]
              else:
                  final_data["priority_data"][key] = value

      # final_data
      print("finalData",final_data)
      return {
            'success': True,
            'data': final_data,
            'message':"final_data send successfully"
        }
    except Exception as e:
        return {'success': False, 'message': str(e)}